package by.shilov.newsSite.action;

public enum ActionNames {
    USER_LIST_ACTION,
    USER_LOGIN_ACTION,
    TO_MAIN_PAGE_ACTION,
    TO_ERROR_PAGE_ACTION,
    USER_REGISTER_ACTION,
    USER_LOGOUT_ACTION,
    CHANGE_LOCAL_ACTION,
    NEWS_BY_CATEGORY_ACTION,
    READ_ARTICLE_ACTION,
    READ_ARTICLE_COMMENTS_ACTION,
    WRITE_COMMENT_ACTION,
    RATE_COMMENT_ACTION,
    TO_PERSONAL_CABINET_ACTION,
    WRITE_ARTICLE_ACTION,
}
